sample_data = '''{
  "amounts":[
    {
      "amount":3,
      "bbd":"2021-09-30T00:00:00Z",
      "comment":"",
      "country_of_disassembly":null,
      "country_of_rearing":null,
      "country_of_slaughter":null,
      "cutting_plant_registration":null,
      "item":{
        "amount_multiplier":24,
        "brand":"Unknown",
        "categ_id":750,
        "category_id":"10000236",
        "code":"004311527127771",
        "description":"Waln\u00fcsse idS 30mm+ FR I 500g BT",
        "edeka_article_number":"80062875",
        "gross_weight":0,
        "id":"2434",
        "net_weight":12000,
        "notes":false,
        "packaging":"PUG",
        "related_products":[

        ],
        "requires_best_before_date":true,
        "requires_meat_info":false,
        "trade_item_unit_descriptor":"CASE",
        "trade_item_unit_descriptor_name":"Karton",
        "type":"gtin",
        "unit_name":"g",
        "validation_status":"validated"
      },
      "lot_number":null,
      "slaughterhouse_registration":null
    },
    {
      "amount":23,
      "bbd":"2022-07-31T00:00:00Z",
      "comment":"",
      "country_of_disassembly":null,
      "country_of_rearing":null,
      "country_of_slaughter":null,
      "cutting_plant_registration":null,
      "item":{
        "amount_multiplier":16,
        "brand":"Alsan-S",
        "categ_id":705,
        "category_id":"10000168",
        "code":"4002724000669",
        "description":"ALSAN-S\u00ae K\u00f6stliche Pflanzen-Margarine 250g 16x",
        "edeka_article_number":false,
        "gross_weight":0,
        "id":"6084",
        "net_weight":4198,
        "notes":false,
        "packaging":"CT",
        "related_products":[

        ],
        "requires_best_before_date":true,
        "requires_meat_info":false,
        "trade_item_unit_descriptor":"CASE",
        "trade_item_unit_descriptor_name":"Karton",
        "type":"gtin",
        "unit_name":"g",
        "validation_status":"validated"
      },
      "lot_number":null,
      "slaughterhouse_registration":null
    }
  ],
  "session_end_time":"2022-04-29T11:56:37.132Z",
  "session_id":1651233397132,
  "session_start_time":"2022-04-29T11:40:14.860Z",
  "supplier_id":"1050",
  "user_id":"adrian@sprk.global"
}'''
