version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-api-dev
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    command: 'sh -c "echo \"Container started\" && while sleep 1; do :; done"'
    depends_on:
      - database

  database:
    image: postgres:12
    container_name: products-api-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_name
    volumes:
      - ./db_mount:/var/lib/postgresql/data
  
  redis:
    image: redis:7.2.7-alpine
    container_name: products-api-redis
  
  celery:
    restart: always
    build:
      context: .
    # command: >
    #   sh -c "cd products_api && celery -A products_api worker -l INFO"
    command: 'sh -c "echo \"Container started\" && while sleep 1; do :; done"'
    volumes:
      - .:/django
    container_name: products-api-celery
    depends_on:
      - database
      - redis
      - dev 
  