version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - products_api/products_api/.env
    container_name: postgres_db
  
  redis:
    image: redis:alpine
    container_name: redis
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products_api_container
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    command: 'sh -c "echo \"Container started\" && while sleep 1; do :; done"'
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    # command: >
    #   sh -c "cd products_api && celery -A products_api worker -l INFO"
    command: 'sh -c "echo \"Container started\" && while sleep 1; do :; done"'
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app 
  