version: '3.8'
services:

  # database 
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - products_api/products_api/.env
    container_name: postgres_db

  # redis
  redis:
    image: redis:alpine
    container_name: redis
  
  # django
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:products_api
    container_name: products_api_container
    command: python3 products_api/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  # celery
  celery:
    restart: always
    build:
      context: .
    command: >
      sh -c "cd products_api && celery -A products_api worker -l INFO"
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app 
  